[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.7.5"

# Description
title = "Humanoid Environments"
description="Extension containing suite of environments for huamnoid."
readme  = "docs/README.md"
repository = "https://github.com/quincy-u/Ego_Humanoid_Manipulation_Benchmark"
category = "robotics"
keywords = ["robotics", "rl", "il", "learning", "humanoid"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}
"omni.isaac.core" = {}
"omni.isaac.gym" = {}
"omni.replicator.isaac" = {}

[[python.module]]
name = "humanoid.tasks"
